# Generated by Django 4.2.6 on 2023-11-30 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_ordereditems_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmorder',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='confirmorder',
            old_name='items',
            new_name='order_id',
        ),
    ]
