# Generated by Django 4.2.6 on 2023-12-30 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_websitefeedback_productfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeedback',
            name='customer_id',
            field=models.ForeignKey(default='8585858585', on_delete=django.db.models.deletion.CASCADE, to='product.customer'),
        ),
        migrations.AddField(
            model_name='websitefeedback',
            name='customer_id',
            field=models.ForeignKey(default='8585858585', on_delete=django.db.models.deletion.CASCADE, to='product.customer'),
        ),
    ]
